version: "3"

services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: 1000
        USER_GID: 1000
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - ..:/workspace:cached
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
  broker:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
